config/routes.rb
Rails.application.routes.draw do
  get 'profile_edits/new'

  root 'incidents#index'
  resources :incidents
  devise_for :accounts, controllers: {registrations: "accounts"}

  devise_scope :account do
    get 'accounts/edit_profile' => 'accounts#edit_profile'
    patch 'accounts/update_profile' => 'accounts#update_profile'
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :database_authenticatable
  
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :phone, :presence => true
  
  has_many :incidents, dependent: :destroy
  after_create :upsert_account_record_sfdc
  include ApplicationHelper
  
  protected
    def upsert_account_record_sfdc
      client = initialize_client
      # don't forget to include the external ID
      client.upsert!('Account', 'Rails_ID__c', Rails_ID__c: id, FirstName: first_name, LastName: last_name, PersonEmail: email, PersonTitle: title, Phone: phone)
      # lookup the record to get the account number
      account_number_will_change!
      self.account_number = client.find('Account', id, 'Rails_ID__c').Id
      self.save!
    end
  
end

app/models/incident.rb
class Incident < ActiveRecord::Base
  belongs_to :account
    
  validates :account, :presence => true
  validates :description, :presence => true
  validates :subject, :presence => true
    
end

app/controllers/accounts_controller.rb
class AccountsController < Devise::RegistrationsController

	 
    before_filter :update_sanitized_params, if: :devise_controller?

    def update_sanitized_params
       devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:first_name, :last_name, :phone, :email, :title, :password, :password_confirmation)}
    end

    def edit_profile
    	@account = current_account
    	render 'devise/registrations/edit_profile'
    end

    def update_profile
    	@account = current_account
    	if @account.update_attributes(account_params)
  		flash[:success] = "Profile updated"
  		update_account_record_sfdc
  		redirect_to root_url
  		else
  		render 'devise/registrations/edit_profile'
  		end
    end


	private
	def account_params
		params.require(:account).permit(:first_name, :last_name, :phone)
	end

	protected

    def update_account_record_sfdc
      client = initialize_client
      # don't forget to include the external ID
      client.upsert!('Account', 'Rails_ID__c', Rails_ID__c: @account.id, FirstName: @account.first_name, LastName: @account.last_name, PersonEmail: @account.email, Phone: @account.phone)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
  include ApplicationHelper

end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :authenticate_account!
  before_action :set_incident, only: [:show, :edit, :update, :destroy]


  # GET /incidents
  # GET /incidents.json
  def index
    @incidents = Incident.where(account: current_account)
    # render 'layouts/front_test'
  end

  # GET /incidents/1
  # GET /incidents/1.json
  def show
  end

  # GET /incidents/new
  def new
    @incident = Incident.new
  end

  # GET /incidents/1/edit
  def edit
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident = Incident.new(incident_params)
    @incident.account = current_account
    @incident.status = "Pending"
    respond_to do |format|
      if @incident.save
        create_incident_record_sfdc
        format.html { redirect_to @incident, notice: 'Incident was successfully created.' }
        format.json { render :show, status: :created, location: @incident }
      else
        format.html { render :new }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incidents/1
  # PATCH/PUT /incidents/1.json
  def update
    # make sure that the account isn't inadvertently changed.
    incident_params[:account] = Incident.find(params[:id]).account
    # back to regular processing
    respond_to do |format|
      if @incident.update(incident_params)
        format.html {
          update_incident_record_sfdc
        redirect_to @incident, notice: 'Incident was successfully updated.' }
        format.json {
          render :show, status: :ok, location: @incident
        }
      else
        @incident.error.each do |message|
          puts message
        end
        format.html { render :edit }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident.destroy
    respond_to do |format|
      format.html { redirect_to incidents_url, notice: 'Incident was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_incident
    @incident = Incident.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def incident_params
    params.require(:incident).permit(:incident_number, :closed_date, :description, :is_closed, :status, :subject, :account_id, :latitude, :longitude)
  end

  def update_incident_record_sfdc
    client = initialize_client
    client.upsert!('Case','Rails_ID__c', Rails_ID__c: @incident.id, Description: @incident.description, Subject: @incident.subject, AccountId: @incident.account.account_number)
  end

  def create_incident_record_sfdc
    client = initialize_client
    randomize_incident_id
    # don't forget to include the external ID
    client.create!('Case', Rails_ID__c: @incident.id, Description: @incident.description, Subject: @incident.subject, AccountId: @incident.account.account_number, location__latitude__s: @incident.latitude.round(3), location__longitude__s: @incident.longitude.round(3) )
    @incident.incident_number =  client.find('Case', @incident.id, 'Rails_ID__c').CaseNumber
    @incident.save!
  end

  def randomize_incident_id
    @incident.id = Time.now.to_i
  end

  def retrieve_geocode_of_request
    # returns Geocoder::Result object
    request.location.data
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def initialize_client
      Restforce.new :username => Rails.application.secrets.sfdc_user_name,
       :password => Rails.application.secrets.sfdc_password,
       :security_token => Rails.application.secrets.sfdc_security_token,
       :client_id      => Rails.application.secrets.sfdc_client_id,
       :client_secret  => Rails.application.secrets.sfdc_client_secret
    end 

    # def gravatar_for(user, options={size: 100})
	   #  gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	   #  size = options[:size]
	   #  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	   #  image_tag(gravatar_url, alt: user.first_name, class: "gravatar")
    # end 
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/_edit_incident_form.html.erb
<%= form_for(@incident) do |f| %>
  <% if @incident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incident.errors.count, "error") %> prohibited this incident from being saved:</h2>

      <ul>
      <% @incident.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject, :size => 82 %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :rows => 10, :cols => 80 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



app/views/incidents/_new_incident_form.html.erb
<%= form_for(@incident) do |f| %>
  <% if @incident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incident.errors.count, "error") %> prohibited this incident from being saved:</h2>

      <ul>
      <% @incident.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject, :size => 82 %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :rows => 10, :cols => 80 %>
  </div>
  <div class="container">
	<div class="row">
		<div class="col-md-12">
			<div id='map'></div>
			<pre id='coordinates' class='ui-coordinates'>Drag the red marker to provide the incident's geolocation!</pre>
		</div>
	</div>
   </div>

   <%= f.hidden_field :latitude, value: "0" %>
   <%= f.hidden_field :longitude, value: "0" %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incidents/edit.html.erb
<h1>Editing Incident</h1>

<%= render 'edit_incident_form' %>

<%= link_to 'Show', @incident %> |
<%= link_to 'Back', incidents_path %>

app/views/incidents/index.html.erb
<p id="notice"><%= notice %></p>

<!-- <div class="center"> <h1>My Incidents</h1> </div> -->

<h1>My Incidents</h1>

<table class="table",border="1">
  <thead>
    <tr>
      <th>Incident number</th>
      <th>Subject</th>
      <th>Status</th>
      <th>Is closed</th>
      <th>Closed date</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @incidents.each do |incident| %>
      <tr>
        <td><%= incident.incident_number %></td>
        <td><%= incident.subject %></td>
        <td><%= incident.status %></td>
        <td><%= incident.is_closed %></td>
        <td><%= incident.closed_date %></td>
        <td><%= link_to 'Show', incident %></td>
        <td><%= link_to 'Edit', edit_incident_path(incident) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Incident', new_incident_path %>

app/views/incidents/new.html.erb
<h1>New Incident</h1>

<%= javascript_include_tag :map %>

<%= render 'new_incident_form' %>


<%= link_to 'Back', incidents_path %>

app/views/incidents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Incident number:</strong>
  <%= @incident.incident_number %>
</p>

<p>
  <strong>Closed date:</strong>
  <%= @incident.closed_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @incident.description %>
</p>

<p>
  <strong>Is closed:</strong>
  <%= @incident.is_closed %>
</p>

<p>
  <strong>Status:</strong>
  <%= @incident.status %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @incident.subject %>
</p>

<%= link_to 'Edit', edit_incident_path(@incident) %> |
<%= link_to 'Back', incidents_path %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
       <% if account_signed_in? %>
       <li><%= link_to "Home",   root_path %></li>
     <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_account.reload.first_name %>'s account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to 'Account Settings', edit_account_registration_path %> </li>
              <li class="divider"></li>
              <li> <%= link_to 'Update My Profile', accounts_edit_profile_path %> 
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_account_session_path, method: "delete"%>
              </li>
            </ul>
      </li>

        <% else %>
        <li><%= link_to "Log in", new_account_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Incident Management System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
<script src='https://api.tiles.mapbox.com/mapbox.js/v2.2.1/mapbox.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox.js/v2.2.1/mapbox.css' rel='stylesheet' />



</head>

<body>
    <%= render 'layouts/header' %>
<%= yield %>

</body>
</html>